// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:e3464c30-b44b-44b7-bdd2-04fc060697bc',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'helloworld-hosting-mobilehub-236898458',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ebjol6z2xvyz.cloudfront.net',
    'aws_mobile_analytics_app_id': '686748fd658a4798958359cca0769b7e',
    'aws_project_id': '17e2b18f-f938-4b61-ae2c-c80f1f847621',
    'aws_project_name': 'hello-world-2018-01-01-19-44-39',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'helloworld-mobilehub-236898458',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_sN92q9M0B',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3lrpb2qtjsgdun95qigb23hmt4',
}

export default awsmobile;
